### ISSUE TITLE
Does not fetch lists

### ISSUE THREAD

**Issue by FuzzyMistborn** [kevdliu/hassio-addon-anylist#6]
When I first set this up, I managed to pull 2 of my 8 lists into HA.  I tried setting the default list to the main one I really was after (Groceries) but now nothing displays.  Seeing this in the logs:

```
> anylist@1.0.0 start
> node index.js --credentials-file /data/.anylist_credentials
Server port: 9000
Credentials file: /data/.anylist_credentials
/anylist/node_modules/anylist/lib/index.js:256
		this.ws.close();
		        ^
TypeError: Cannot read properties of undefined (reading 'close')
    at AnyList.teardown (/anylist/node_modules/anylist/lib/index.js:256:11)
    at initialize (/anylist/index.js:22:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /anylist/index.js:217:17
Node.js v18.19.1
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
npm notice Run `npm install -g npm@10.5.0` to update!
npm notice 
> anylist@1.0.0 start
> node index.js --credentials-file /data/.anylist_credentials
Server port: 9000
Credentials file: /data/.anylist_credentials
/anylist/node_modules/anylist/lib/index.js:256
		this.ws.close();
		        ^
TypeError: Cannot read properties of undefined (reading 'close')
    at AnyList.teardown (/anylist/node_modules/anylist/lib/index.js:256:11)
    at initialize (/anylist/index.js:22:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /anylist/index.js:217:17
Node.js v18.19.1
> anylist@1.0.0 start
> node index.js --credentials-file /data/.anylist_credentials
Server port: 9000
Credentials file: /data/.anylist_credentials
```

**Comment by kevdliu** [comment]
Thanks for the bug report. The bug lives in the upstream anylist library but I'm a maintainer of that project too so I'll fix it there.

**Comment by kevdliu** [comment]
Just pushed v1.71 which should have it fixed

**Comment by FuzzyMistborn** [comment]
I also realized I had quotes around my password which it didn't seem to like.  I'm seeing all my lists now, thanks!
